name: copilot-setup-steps

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Debug setup
        run: echo "SETUP FILE IS RUNNING"

      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - run: npm install
